# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="re5et"

# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="cd ~/.oh-my-zsh"
alias zz="source ~/.zshrc"

alias pb="ping www.baidu.com"

alias egrep="grep -E"
alias fgrep="grep -F"
alias pacman='sudo pacman'
alias updatedb='sudo /usr/libexec/locate.updatedb'

#servers
if [ -f ~/.ssh/server_alias.sh ]; then
    source ~/.ssh/server_alias.sh
fi

#correction
#alias python='nocorrect python'
DISABLE_CORRECTION="true"
# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx)

# /etc/profile.d/python.sh
source /etc/profile
source $ZSH/oh-my-zsh.sh
if [ -f $HOME/.zprofile ]; then
    source $HOME/.zprofile
fi

PATH=$PY_HOME:$HOME/scripts:$PATH
export PATH

# Customize to your needs...
pip completion --zsh|source /dev/stdin
export EDITOR="vim"

# python
source ${PY_HOME}/virtualenvwrapper.sh

# {ssh}
eval `/usr/local/bin/ssh-attach`
for i in ~/.ssh/{id_rsa,id_rsa_cn6};
do
    if ssh-add -l|grep -q "$i"; then
        continue
    fi
    ssh-add $i
done

# update ssh host alias
if curl --connect-timeout 1 l-pgstats2.h.cn6.qunar.com:54321/ssh_config_alias 2>/dev/null >~/.ssh/config_alias; then
    cat ~/.ssh/config_{head,alias,tail} >~/.ssh/config
fi
